apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolov8-10-ocr-deployment
  labels:
    app: yolov8-ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolov8-ocr
  template:
    metadata:
      labels:
        app: yolov8-ocr
    spec:
      containers:
      - name: yolov8-ocr-container
        image: rgojard/kedro-road-sign:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20