version: "3.13.2"

services:
  kedro:
    # image: rgojard/tp-orchestration-ml:latest
    # container_name: back-end
    build:
      context: ./kedro-road-sign
      dockerfile: Dockerfile
    volumes:
      - ./kedro-road-sign:/app
    ports:
      - "8000:8000"
    environment:
      - KEDRO_ENV=local # =development
    depends_on:
      - kedro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
