# path du data yaml
data_config_path: "data/01_raw/data.yaml"

# path du model entrainé
trained_model_path: "data/06_models/best.pt"

# param for ocr
ocr_lang: "fra"

# param for labels
labels_use_case_path: "data/01_raw/labels/use_case"

# param for images
images_path: "data/01_raw/images/use_case"
# param for api images
image_api_path: "data/01_raw/images/user_uploads"

# images_path_ocr
images_path_ocr: "data/01_raw/images/use_case"

# path for preprocessed images
images_path_preprocessed: "data/05_model_input/images_preprocessed"

images_yolo_predict_input_path: "data/01_raw/images/val"

# cmd local path
cmd_local_path: "/usr/bin/tesseract"

# model path
model_path: "data/06_models/best.pt"

# predict yolo output
yolo_predict_output_dir: "data/07_model_output/yolo_predictions"

# predict results
labels_input: "data/05_model_input/labels_input"