# path du data yaml
data_config_path: "data/01_raw/data.yaml"

# path du model entrainé
trained_model_path: "data/06_models/best.pt"

# path evaluation metrics
yolo_evaluation_metrics: "data/07_evaluation/yolo_evaluation_metrics.json"

# param for ocr
ocr_lang: "fra"

# param for labels
labels_path: "data/01_raw/labels/val"

# param for images
images_path: "data/01_raw/images/val"

# param for ocr_rois
ocr_rois: "data/03_primary/ocr_rois.json"

# cmd local path
cmd_local_path: "/opt/homebrew/bin/tesseract"