name: MLOpsPipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2' # base: 3.10

      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install --upgrade pip
          pip install -r kedro-road-sign/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          cd kedro-road-sign
          pytest

      - name: Build Docker image for kedro
        run: |
          cd kedro-road-sign
          docker build -t rgojard/kedro-road-sign:latest .

      - name: Build Docker image for frontend
        run: |
          cd frontend
          docker build -t rgojard/road-sign-frontend:latest .

      - name: Login to DockerHub
        if: success() # on ne se connecte que si les tests ont reussi
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        if: success() # on ne push que si success 
        run: |
          docker push rgojard/kedro-road-sign:latest
          docker push rgojard/road-sign-frontend:latest
